### PR TITLE
add link to strange guy playing accordion

### PR DESCRIPTION
**Pull request by matthew-black**
@Bontgoy

### CODE REVIEW

**Comment by Bontgoy** [comment]
Looks good @matthew-black!

:shipit:

**Comment by Bontgoy** [comment]
@matthew-black you should be merging this branch to master not closing it.  Let me know if you have questions.

**Comment by matthew-black** [comment]
@Bontgoy I didn't know we'd want to "keep" the little change we were told to make. Should I put that youtube link back in?

**Comment by Bontgoy** [comment]
@matthew-black That's fine.  If you have merged elsewhere but the assignments you push up to github should definitely be merged to your master after submitting .

**Comment by matthew-black** [comment]
@Bontgoy Roger that!

**Pull request closed without merging**
